# Exercício - Aula 3 – Redes Neurais Artificiais

In [1]:
import numpy as np

# Função logística (sigmoide)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivada da função logística
def sigmoid_derivative(x):
    return x * (1 - x)

# Dados de entrada e saída desejada
X = np.array([
    [1, 0, 0, 1, 0],
    [1, 0, 0, 0, 1],
    # ... Adicione os outros exemplos de entrada aqui
])

y = np.array([
    [1, 0],
    [1, 0],
    # ... Adicione os outros exemplos de saída desejada aqui
])

# Inicialização dos pesos da rede
input_size = X.shape[1]
hidden_size = 5
output_size = 2

np.random.seed(0)
weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))

In [2]:
# Hiperparâmetros
learning_rate = 0.1
error_threshold = 0.01
max_epochs = 10000

# Treinamento da rede
for epoch in range(max_epochs):
    # Forward pass
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output_layer_output = sigmoid(output_layer_input)

    # Cálculo do erro
    error = y - output_layer_output
    mean_squared_error = np.mean(error ** 2)

    if mean_squared_error < error_threshold:
        print(f"Treinamento concluído na época {epoch} com erro quadrático médio {mean_squared_error:.5f}")
        break

    # Backpropagation
    d_output = error * sigmoid_derivative(output_layer_output)
    error_hidden_layer = d_output.dot(weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    # Atualização dos pesos
    weights_hidden_output += hidden_layer_output.T.dot(d_output) * learning_rate
    weights_input_hidden += X.T.dot(d_hidden_layer) * learning_rate

    if epoch % 1000 == 0:
        print(f"Época {epoch}: Erro quadrático médio = {mean_squared_error:.5f}")

# Resultados finais
print("Pesos da camada oculta para a camada de saída:")
print(weights_hidden_output)
print("Pesos da camada de entrada para a camada oculta:")
print(weights_input_hidden)

Época 0: Erro quadrático médio = 0.28069
Treinamento concluído na época 93 com erro quadrático médio 0.00992
Pesos da camada oculta para a camada de saída:
[[ 0.69748178 -0.63387558]
 [ 1.00208546 -0.25580889]
 [ 0.47590818 -0.54786652]
 [ 0.83590095 -0.3676671 ]
 [ 0.62561764 -0.73052118]]
Pesos da camada de entrada para a camada oculta:
[[0.60399947 0.70268437 0.63266462 0.54642612 0.50402409]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.12106404 0.0136294  0.84621298 0.77953917 0.90370729]
 [0.99986957 0.79324257 0.47778747 0.7806897  0.16494857]]
